name: PahanaEduService Maven build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Workaround: install mysql-connector-java but under the artifactId "mysql-connector-j"
    - name: Install MySQL Connector workaround
      run: |
        curl -L -o mysql-connector-java-8.0.32.jar https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.32/mysql-connector-java-8.0.32.jar
        mvn install:install-file \
          -Dfile=mysql-connector-java-8.0.32.jar \
          -DgroupId=mysql \
          -DartifactId=mysql-connector-j \
          -Dversion=8.0.32 \
          -Dpackaging=jar

    - name: Build with Maven (skip tests)
      working-directory: PahanaEduService/
      run: mvn clean install -Dmaven.test.skip=true
